//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_MVCwebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class before_stemmer
    {
        public string doc_id { get; set; }
        public string term { get; set; }
        public int id { get; set; }
    }
}
