//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_MVCwebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class crawler_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crawler_data()
        {
            this.tockenzs = new HashSet<tockenz>();
        }
    
        public int id { get; set; }
        public string URL { get; set; }
        public string content_data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tockenz> tockenzs { get; set; }
    }
}
